-- ==============================================
-- DELIVERABLE 5: Admin Analytics & Telemetry Schema
-- ==============================================

-- 1. Create the `analytics_events` table for event sourcing
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index the event_type and created_at columns for fast timeseries querying
CREATE INDEX IF NOT EXISTS idx_analytics_events_type_time 
ON public.analytics_events(event_type, created_at DESC);

-- 2. Create a generic function to fetch the "Most Difficult Module" dynamically
CREATE OR REPLACE FUNCTION get_most_difficult_modules(days_back INT DEFAULT 7)
RETURNS TABLE (module_name TEXT, failure_count BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        (metadata->>'module')::TEXT as module_name,
        COUNT(*) as failure_count
    FROM public.analytics_events
    WHERE event_type = 'ai_failure' 
    AND created_at >= NOW() - (days_back || ' days')::INTERVAL
    AND metadata->>'module' IS NOT NULL
    GROUP BY metadata->>'module'
    ORDER BY failure_count DESC
    LIMIT 5;
END;
$$ LANGUAGE plpgsql;

-- 3. Create a view for daily engagement metrics to speed up dashboard loads
CREATE OR REPLACE VIEW daily_engagement_metrics AS
SELECT 
    date_trunc('day', created_at) AS report_date,
    COUNT(DISTINCT user_id) FILTER (WHERE event_type = 'session_start') AS daily_active_users,
    COUNT(*) FILTER (WHERE event_type = 'course_enroll') AS new_enrollments,
    COUNT(*) FILTER (WHERE event_type = 'module_complete') AS completed_modules,
    COUNT(*) FILTER (WHERE event_type = 'ai_failure') AS total_tracker_failures
FROM public.analytics_events
GROUP BY date_trunc('day', created_at)
ORDER BY report_date DESC;
