-- ==============================================
-- DELIVERABLE 1 & 2: Foreign Keys & Relationships
-- ==============================================

-- 0. Ensure `users` table exists (If it already exists in your DB, this step skips gracefully)
-- We use BIGINT for id because your existing users table is using BIGINT instead of UUID.
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    username TEXT UNIQUE,
    email TEXT UNIQUE,
    role TEXT DEFAULT 'student',
    password_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1. Ensure `courses` table exists with visually rich fields needed for the frontend
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    gestures JSONB,
    mastery_score INTEGER,
    difficulty TEXT,
    modules INTEGER,
    duration TEXT,
    icon TEXT,
    color TEXT,
    premium BOOLEAN DEFAULT false,
    "desc" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the `enrollments` table with strict Foreign Keys targeting both users and courses.
CREATE TABLE IF NOT EXISTS public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    course_id BIGINT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    -- Composite unique key to ensure a user can only buy a course once
    UNIQUE (user_id, course_id)
);

-- 3. Create a `transactions` table for auditing mock payments
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    amount DECIMAL(10, 2) NOT NULL,
    payment_status TEXT DEFAULT 'completed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ==============================================
-- DELIVERABLE 3: Multi-table Transactions + Integrity
-- ==============================================

-- 4. Create Postgres RPC (Stored Procedure).
-- This block binds insertion of a transaction and an enrollment securely.
-- If the enrollment fails (e.g. they already own it), the transaction rolls back so they are not charged.
CREATE OR REPLACE FUNCTION purchase_course(
    p_user_id BIGINT, 
    p_course_id BIGINT, 
    p_amount DECIMAL
)
RETURNS boolean AS $$
BEGIN
    -- 1. Insert into transactions
    INSERT INTO public.transactions (user_id, amount, payment_status)
    VALUES (p_user_id, p_amount, 'completed');

    -- 2. Insert into enrollments
    INSERT INTO public.enrollments (user_id, course_id, status)
    VALUES (p_user_id, p_course_id, 'active');

    RETURN true;
EXCEPTION
    WHEN OTHERS THEN
        -- Rollback trigger
        RAISE EXCEPTION 'Transaction failed: %', SQLERRM;
        RETURN false;
END;
$$ LANGUAGE plpgsql;


-- ==============================================
-- DB SEED (MOCK DATA FOR FRONTEND)
-- ==============================================

-- Seed the live DB so we don't have to rely on hard-coded static arrays in Courses.jsx
-- If courses already exist with these titles, they might duplicate, but for our demo, this is fine or you can truncate `courses` first.
INSERT INTO public.courses (title, difficulty, modules, duration, icon, color, premium, "desc")
VALUES 
('AI Real-Time: Alphabet Basics', 'Beginner', 5, '2 Hours', '🤖', '#14b8a6', false, 'Use your camera to get instant AI corrections. This module tests your ability to accurately sign A, B, and V.'),
('Visual Tracking: Speed', 'Intermediate', 8, '3.5 Hours', '🔥', '#f59e0b', false, 'Analyze your motion flow and speed using our proprietary visual heatmap tracking tech.'),
('Contextual: Daily Life', 'Beginner', 4, '1.5 Hours', '🛒', '#3b82f6', false, 'Master situational awareness and practical signs for grocery shopping and traveling.'),
('Healthcare: ER Triage', 'Advanced', 10, '5 Hours', '⚕️', '#ef4444', true, 'Bridging the gap in medical settings. Ensure clear, accurate communication when it matters most.'),
('Healthcare: Consent', 'Advanced', 12, '6 Hours', '🏥', '#ec4899', true, 'Accurate ASL communication tailored for medical consent and complicated procedures.');
