-- ==============================================
-- SignSync Database Setup (Canonical Schema)
-- ==============================================
-- This script provisions a fresh environment.
-- It reflects the current production model where
-- course access is governed by user membership_status
-- (not a per-course premium flag).

-- 0. Ensure `users` table exists
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    username TEXT UNIQUE,
    email TEXT UNIQUE,
    role TEXT DEFAULT 'student',
    password_hash TEXT,
    membership_status TEXT DEFAULT 'free',
    membership_expires_at TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1. Ensure `courses` table exists
-- Access control is derived from the `difficulty` column:
--   beginner / intermediate = free for all users
--   advanced = requires membership_status = 'member'
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    gestures JSONB,
    mastery_score INTEGER,
    difficulty TEXT,
    modules INTEGER,
    duration TEXT,
    icon TEXT,
    color TEXT,
    "desc" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the `enrollments` table with strict Foreign Keys
CREATE TABLE IF NOT EXISTS public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    course_id BIGINT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, course_id)
);

-- 3. Create a `transactions` table for auditing membership changes
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    amount DECIMAL(10, 2) NOT NULL,
    payment_status TEXT DEFAULT 'completed',
    transaction_type TEXT DEFAULT 'membership_upgrade',
    reference TEXT DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ==============================================
-- DB SEED (MOCK DATA FOR FRONTEND)
-- ==============================================

INSERT INTO public.courses (title, difficulty, modules, duration, icon, color, "desc", gestures)
VALUES 
('AI Real-Time: Alphabet Basics', 'Beginner', 5, '2 Hours', '🤖', '#14b8a6', 'Use your camera to get instant AI corrections. This module tests your ability to accurately sign A, B, and V.', '["A", "B", "C", "D", "E"]'::jsonb),

('Contextual: Daily Life', 'Beginner', 4, '1.5 Hours', '🛒', '#3b82f6', 'Master situational awareness and practical signs for grocery shopping and traveling.', '["A", "E", "I", "O", "U"]'::jsonb),
('Healthcare: ER Triage', 'Advanced', 10, '5 Hours', '⚕️', '#ef4444', 'Bridging the gap in medical settings. Ensure clear, accurate communication when it matters most.', '["F", "G", "H", "P", "Q"]'::jsonb),
('Healthcare: Consent', 'Advanced', 12, '6 Hours', '🏥', '#ec4899', 'Accurate ASL communication tailored for medical consent and complicated procedures.', '["F", "G", "H", "P", "Q"]'::jsonb);
