-- ==============================================
-- DELIVERABLE: Course Progress Tracking
-- ==============================================

-- Create the course_progress table to track individual module completions
CREATE TABLE IF NOT EXISTS public.course_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    course_id BIGINT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
    module_name TEXT NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, course_id, module_name)
);

-- Index for fast lookup when computing enrollment progress
CREATE INDEX IF NOT EXISTS idx_course_progress_user_course 
ON public.course_progress(user_id, course_id);
